module load gcc/11.3.0
module load openmpi/4.1.4--gcc--11.3.0-cuda-11.8
module load cuda/11.8  
module load superlu-dist/8.1.1--openmpi--4.1.4--gcc--11.3.0-cuda-11.8
module load mumps/5.5.1--openmpi--4.1.4--gcc--11.3.0
module load metis/5.1.0--gcc--11.3.0
module load parmetis/4.0.3--openmpi--4.1.4--gcc--11.3.0 
module load openblas/0.3.21--gcc--11.3.0
module load hypre/2.26.0--openmpi--4.1.4--gcc--11.3.0-cuda-11.8
module load netlib-scalapack/2.2.0--openmpi--4.1.4--gcc--11.3.0 
module load eigen/3.4.0--gcc--12.2.0-5jcagas
module load fftw/3.3.10--openmpi--4.1.4--gcc--11.3.0
module load zlib/1.2.13--gcc--11.3.0
module load cmake/3.27.7

#module load lua/5.4.4--gcc--12.2.0 
#module load petsc/3.19.0--openmpi--4.1.4--gcc--11.3.0-cuda-11.8

export LD_LIBRARY_PATH=/leonardo/prod/opt/compilers/cuda/11.8/none/lib64/stubs:$LD_LIBRARY_PATH

"""
#  cd petsc-3.19.0
$> srun -p boost_usr_prod --qos=boost_qos_dbg --nodes=1 --mem=0 --tasks-per-node=1 --cpus-per-task=32 -t 00:30:00 --gres=gpu:4 --pty bash
$> ./config/configure.py --prefix=/leonardo_work/cin_staff/mcelori1/ChEESE/PETSc/petsc-3.19.0-opt --with-ssl=0 --download-c2html=0 --download-sowing=0 --download-hwloc=0 --with-cc=${MPICC} --with-cxx=${MPICXX} --with-fc=${MPIF90} --with-precision=double --with-scalar-type=real --with-shared-libraries=1 --with-debugging=0 --with-openmp=0 --with-64-bit-indices=0 --with-blaslapack-lib=${OPENBLAS_LIB}/libopenblas.so --with-x=0 --with-clanguage=C --with-cuda=1 --with-cuda-dir=${CUDA_HOME} --with-hip=0 --with-metis=1 --with-metis-include=${METIS_INC} --with-metis-lib=${METIS_LIB}/libmetis.so --with-hypre=1 --with-hypre-include=${HYPRE_INC} --with-hypre-lib=${HYPRE_LIB}/libHYPRE.so --with-parmetis=1 --with-parmetis-include=${PARMETIS_INC} --with-parmetis-lib=${PARMETIS_LIB}/libparmetis.so --with-kokkos=0 --with-kokkos-kernels=0 --with-superlu_dist=1 --with-superlu_dist-include=${SUPERLU_DIST_INC} --with-superlu_dist-lib=${SUPERLU_DIST_LIB}/libsuperlu_dist.so --with-ptscotch=0 --with-suitesparse=0 --with-hdf5=1 --with-hdf5-include=${HDF5_INC} --with-hdf5-lib="${HDF5_LIB}/libhdf5_hl_fortran.so ${HDF5_LIB}/libhdf5_hl_f90cstub.so ${HDF5_LIB}/libhdf5_hl.so ${HDF5_LIB}/libhdf5_fortran.so ${HDF5_LIB}/libhdf5_f90cstub.so ${HDF5_LIB}/libhdf5.so" --with-zlib=1 --with-zlib-include=${ZLIB_INC} --with-zlib-lib=${ZLIB_LIB}/libz.so --with-mumps=1 --with-mumps-include=${MUMPS_INC} --with-mumps-lib="${MUMPS_LIB}/libcmumps.so ${MUMPS_LIB}/libsmumps.so ${MUMPS_LIB}/libdmumps.so ${MUMPS_LIB}/libzmumps.so ${MUMPS_LIB}/libmumps_common.so ${MUMPS_LIB}/libpord.so" --with-trilinos=0 --with-fftw=1 --with-fftw-include=${FFTW_INC} --with-fftw-lib="${FFTW_LIB}/libfftw3_mpi.so ${FFTW_LIB}/libfftw3.so" --with-valgrind=0 --with-gmp=0 --with-libpng=0 --with-giflib=0 --with-mpfr=0 --with-netcdf=0 --with-pnetcdf=0 --with-moab=0 --with-random123=0 --with-exodusii=0 --with-cgns=0 --with-memkind=0 --with-p4est=0 --with-saws=0 --with-yaml=0 --with-hwloc=0 --with-libjpeg=0 --with-scalapack=1 --with-scalapack-lib=${NETLIB_SCALAPACK_LIB}/libscalapack.so --with-strumpack=0 --with-mmg=0 --with-parmmg=0 --with-tetgen=0 --with-cuda-arch=80 --FOPTFLAGS=-O3 --CXXOPTFLAGS=-O3 --COPTFLAGS=-O3
$> make PETSC_DIR=/leonardo_work/cin_staff/mcelori1/ChEESE/PETSc/petsc-3.19.6 PETSC_ARCH="arch-linux-c-opt" all
$> make PETSC_DIR=/leonardo_work/cin_staff/mcelori1/ChEESE/PETSc/petsc-3.19.6 PETSC_ARCH=arch-linux-c-opt install
$> make PETSC_DIR=/leonardo_work/cin_staff/mcelori1/ChEESE/PETSc/petsc-3.19.6-opt PETSC_ARCH="" check
$> cd ..
$> exit
./config/configure.py --prefix=/leonardo_work/cin_staff/mredenti/ChEESE/TANDEM/petsc-3.20.1-opt --with-ssl=0 --download-c2html=0 --download-sowing=0 --download-hwloc=0 --with-cc=${MPICC} --with-cxx=${MPICXX} --with-fc=${MPIF90} --with-precision=double --with-scalar-type=real --with-shared-libraries=1 --with-debugging=0 --with-openmp=0 --with-64-bit-indices=0 --with-blaslapack-lib=${OPENBLAS_LIB}/libopenblas.so --with-x=0 --with-clanguage=C --with-cuda=1 --with-cuda-dir=${CUDA_HOME} --with-hip=0 --with-metis=1 --with-metis-include=${METIS_INC} --with-metis-lib=${METIS_LIB}/libmetis.so --with-hypre=1 --with-hypre-include=${HYPRE_INC} --with-hypre-lib=${HYPRE_LIB}/libHYPRE.so --with-parmetis=1 --with-parmetis-include=${PARMETIS_INC} --with-parmetis-lib=${PARMETIS_LIB}/libparmetis.so --with-kokkos=0 --with-kokkos-kernels=0 --with-superlu_dist=1 --with-superlu_dist-include=${SUPERLU_DIST_INC} --with-superlu_dist-lib=${SUPERLU_DIST_LIB}/libsuperlu_dist.so --with-ptscotch=0 --with-suitespars --with-zlib=1 --with-zlib-include=${ZLIB_INC} --with-zlib-lib=${ZLIB_LIB}/libz.so --with-mumps=1 --with-mumps-include=${MUMPS_INC} --with-mumps-lib="${MUMPS_LIB}/libcmumps.so ${MUMPS_LIB}/libsmumps.so ${MUMPS_LIB}/libdmumps.so ${MUMPS_LIB}/libzmumps.so ${MUMPS_LIB}/libmumps_common.so ${MUMPS_LIB}/libpord.so" --with-trilinos=0 --with-fftw=1 --with-fftw-include=${FFTW_INC} --with-fftw-lib="${FFTW_LIB}/libfftw3_mpi.so ${FFTW_LIB}/libfftw3.so" --with-valgrind=0 --with-gmp=0 --with-libpng=0 --with-giflib=0 --with-mpfr=0 --with-netcdf=0 --with-pnetcdf=0 --with-moab=0 --with-random123=0 --with-exodusii=0 --with-cgns=0 --with-memkind=0 --with-memalign=64 --with-p4est=0 --with-saws=0 --with-yaml=0 --with-hwloc=0 --with-libjpeg=0 --with-scalapack=1 --with-scalapack-lib=${NETLIB_SCALAPACK_LIB}/libscalapack.so --with-strumpack=0 --with-mmg=0 --with-parmmg=0 --with-tetgen=0 --with-cuda-arch=80 --FOPTFLAGS=-O3 --CXXOPTFLAGS=-O3 --COPTFLAGS=-O3
./config/configure.py --prefix=/leonardo_work/cin_staff/mredenti/ChEESE/TANDEM/petsc-3.21.5-opt --with-ssl=0 --download-c2html=0 --download-sowing=0 --download-hwloc=0 --with-cc=${MPICC} --with-cxx=${MPICXX} --with-fc=${MPIF90} --with-precision=double --with-scalar-type=real --with-shared-libraries=1 --with-debugging=0 --with-openmp=0 --with-64-bit-indices=0 --with-blaslapack-lib=${OPENBLAS_LIB}/libopenblas.so --with-x=0 --with-clanguage=C --with-cuda=1 --with-cuda-dir=${CUDA_HOME} --with-hip=0 --with-metis=1 --with-metis-include=${METIS_INC} --with-metis-lib=${METIS_LIB}/libmetis.so --with-hypre=1 --with-hypre-include=${HYPRE_INC} --with-hypre-lib=${HYPRE_LIB}/libHYPRE.so --with-parmetis=1 --with-parmetis-include=${PARMETIS_INC} --with-parmetis-lib=${PARMETIS_LIB}/libparmetis.so --with-kokkos=0 --with-kokkos-kernels=0 --with-superlu_dist=1 --with-superlu_dist-include=${SUPERLU_DIST_INC} --with-superlu_dist-lib=${SUPERLU_DIST_LIB}/libsuperlu_dist.so --with-ptscotch=0 --with-suitespars --with-zlib=1 --with-zlib-include=${ZLIB_INC} --with-zlib-lib=${ZLIB_LIB}/libz.so --with-mumps=1 --with-mumps-include=${MUMPS_INC} --with-mumps-lib="${MUMPS_LIB}/libcmumps.so ${MUMPS_LIB}/libsmumps.so ${MUMPS_LIB}/libdmumps.so ${MUMPS_LIB}/libzmumps.so ${MUMPS_LIB}/libmumps_common.so ${MUMPS_LIB}/libpord.so" --with-trilinos=0 --with-fftw=1 --with-fftw-include=${FFTW_INC} --with-fftw-lib="${FFTW_LIB}/libfftw3_mpi.so ${FFTW_LIB}/libfftw3.so" --with-valgrind=0 --with-gmp=0 --with-libpng=0 --with-giflib=0 --with-mpfr=0 --with-netcdf=0 --with-pnetcdf=0 --with-moab=0 --with-random123=0 --with-exodusii=0 --with-cgns=0 --with-memkind=0 --with-memalign=64 --with-p4est=0 --with-saws=0 --with-yaml=0 --with-hwloc=0 --with-libjpeg=0 --with-scalapack=1 --with-scalapack-lib=${NETLIB_SCALAPACK_LIB}/libscalapack.so --with-strumpack=0 --with-mmg=0 --with-parmmg=0 --with-tetgen=0 --with-cuda-arch=80 --FOPTFLAGS=-O3 --CXXOPTFLAGS=-O3 --COPTFLAGS=-O3
"""