#
# This file was automatically generated by ReFrame based on 'setup_files/settings.py'.  # noqa: E501
#


site_configuration = {
    "systems": [
        {
            "name": "leonardo",
            "descr": "LEONARDO",
            "hostnames": ["login"],
            "modules_system": "tmod4",
            "partitions": [
                {
                    "name": "login",
                    "descr": "LEONARDO Login Nodes",
                    "scheduler": "local",
                    "launcher": "local",
                    "modules": [],
                    "access": [],
                    "max_jobs": 1,
                    "environs": ["default", "gnu", "nvhpc", "nvhpc-24.3", "intel"],
                    "processor": {
                        "num_cpus": 32,
                        "num_cpus_per_core": 1,
                        "num_cpus_per_socket": 32,
                        "num_sockets": 1,
                    },
                },
                {
                    "name": "booster",
                    "descr": "LEONARDO Booster partition",
                    "scheduler": "slurm",
                    "launcher": "srun",
                    "modules": [],
                    "access": ["--partition=boost_usr_prod"],
                    "resources": [
                        {"name": "nodes", "options": ["--nodes={nodes}"]},
                        {"name": "qos", "options": ["--qos={qos}"]},
                        {"name": "account", "options": ["--account={account}"]},
                        {"name": "gpu", "options": ["--gres=gpu:{num_gpus_per_node}"]},
                        {"name": "cpufreq", "options": ["--cpu-freq={cpufreq}"]},
                    ],
                    "max_jobs": 10,
                    "environs": [
                        "default",
                        "gnu",
                        "gnu-mpi",
                        "nvhpc",
                        "nvhpc-24.3",
                        "intel",
                    ],
                    "processor": {
                        "num_cpus": 32,
                        "num_cpus_per_core": 1,
                        "num_cpus_per_socket": 32,
                        "num_sockets": 1,
                    },
                },
                {
                    "name": "dcgp",
                    "descr": "LEONARDO Data Centric General Purpose (DCGP) partition",
                    "scheduler": "slurm",
                    "launcher": "srun",
                    "max_jobs": 8,
                    "modules": [],
                    "access": ["--partition=dcgp_usr_prod"],
                    "resources": [
                        {"name": "qos", "options": ["--qos={qos}"]},
                        {"name": "account", "options": ["--account={account}"]},
                    ],
                    "environs": ["default", "gnu", "intel"],
                    "processor": {
                        "num_cpus": 112,
                        "num_cpus_per_core": 1,
                        "num_cpus_per_socket": 56,
                        "num_sockets": 2,
                    },
                },
            ],
        },
    ],
    "environments": [
        {
            "name": "default",
            "modules": [],
            "cc": "gcc",
            "cxx": "g++",
            "ftn": "gfortran",
            "features": ["openmp"],
            "extras": {"omp_flag": "-fopenmp"},
        },
        {
            "name": "gnu",
            "modules": ["gcc/12.2.0"],
            "cc": "gcc",
            "cxx": "g++",
            "ftn": "f90",
            "features": ["openmp"],
            "extras": {"omp_flag": "-fopenmp"},
        },
        {
            "name": "gnu-mpi",
            "modules": ["gcc/12.2.0", "openmpi/4.1.6--gcc--12.2.0"],
            "cc": "mpicc",
            "cxx": "mpic++",
            "features": ["openmp", "mpi"],
            "extras": {"omp_flag": "-fopenmp"},
        },
        {
            "name": "cuda",
            "modules": ["cuda/12.1", "gcc/12.2.0"],
            "cc": "gcc",
            "cxx": "g++",
            "ftn": "gfortran",
            "features": ["openmp", "cuda"],
            "extras": {"omp_flag": "-fopenmp"},
        },
        {
            "name": "nvhpc",
            "modules": ["nvhpc/23.11", "openmpi/4.1.6--nvhpc--23.11"],
            "cc": "nvcc",
            "cxx": "nvc++",
            "ftn": "nvf90",
            "features": ["openmp", "mpi"],
            "extras": {"omp_flag": "-fopenmp"},
        },
        {
            "name": "nvhpc-24.3",
            "modules": ["nvhpc/24.3", "openmpi/4.1.6--nvhpc--24.3"],
            "cc": "nvcc",
            "cxx": "nvc++",
            "ftn": "nvf90",
            "features": ["openmp", "mpi"],
            "extras": {"omp_flag": "-fopenmp"},
        },
        {
            "name": "intel",
            "modules": ["intel-one-api-compilers"],
        },
    ],
    "logging": [
        {
            "level": "debug",
            "handlers": [
                {
                    "type": "file",
                    "name": "reframe.log",
                    "level": "debug",
                    "format": "[%(asctime)s] %(levelname)s: %(check_name)s: %(message)s",  # noqa: E501
                    "append": False,
                },
                {
                    "type": "stream",
                    "name": "stdout",
                    "level": "info",
                    "format": "%(message)s",
                },
                {
                    "type": "file",
                    "name": "reframe.out",
                    "level": "info",
                    "format": "%(message)s",
                    "append": False,
                },
            ],
            "handlers_perflog": [
                {
                    "type": "filelog",
                    "prefix": "%(check_system)s/%(check_partition)s",
                    "level": "info",
                    "format": (
                        "%(asctime)s,"
                        "%(check_job_completion_time)s,"
                        "reframe %(version)s,"
                        "%(check_info)s,"
                        "%(check_modules)s,"
                        "%(check_result)s,"
                        "%(check_executable)s,"
                        "%(check_executable_opts)s,"
                        "%(check_system)s,"
                        "%(check_environ)s,"
                        "%(check_partition)s,"
                        "%(check_environ)s,"
                        "%(check_descr)s,"
                        "%(check_num_nodes)s,"
                        "%(check_num_tasks_per_node)s,"
                        "%(check_num_cpus_per_task)s,"
                        "%(check_num_gpus_per_node)s,"
                        "%(check_num_tasks)s,"
                        "%(check_exclusive_access)s,"
                        "%(check_perfvalues)s"
                    ),
                    "format_perfvars": ("%(check_perf_value)s," "%(check_perf_unit)s,"),
                    "append": True,
                }
            ],
        }
    ],
    "modes": [
        {
            "name": "maintenance",
            "options": [
                "--exec-policy=async",
                "--reservation=maintenance",
                "--save-log-files",
                "--tag=acceptance",
                "--timestamp=%F_%H-%M-%S",
            ],
        },
    ],
    "general": [{"check_search_path": ["checks/"], "check_search_recursive": True}],
}
